stages:
    - test

variables:
    GIT_SUBMODULE_STRATEGY: recursive

test:
    stage: test
    image: ubuntu
    before_script:
    - apt update
    - apt install g++ cmake ninja-build -y
    script:
    - cmake -H. -Bbuild -GNinja -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic" -DCMAKE_BUILD_TYPE=MinSizeRel
    - cd build
    - ninja
    - ninja test
    artifacts:
        paths:
            - build/Scanner-Preprocessor
